language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: 994ba07d-6922-4898-8269-702a78e04526
  app: virtual-watch-party
  run: rails db:migrate
