require 'rails_helper'

RSpec.describe "Events new page" do
  before(:each) do
    @user = create(:user, username: "StevenSpielberg", email: "stevenspielberg@email.com", password: "Tester", password_confirmation: "Tester")
    @user2 = create(:user, username: "bob", email: "no@email.com", password: "111111", password_confirmation: "111111")
    @user3 = create(:user, username: "frank", email: "yes@email.com", password: "111111", password_confirmation: "111111")

    allow_any_instance_of(ApplicationController).to receive(:current_user).and_return(@user)

    @user.friends << @user2
  end

  it 'has autogenerated values for the event', :vcr do
    @movie = API.movie_by_id(238)
    visit movie_path(@movie)
    click_on "Create Event for #{@movie[:title]}"
    expect(current_path).to eq(new_event_path)

    expect(find_field(:title).value).to eq("#{@movie[:title]}")
    expect(find_field(:duration).value).to eq("#{@movie[:runtime]}")
  end

  describe 'happy path' do
    it 'lets you create a new event', :vcr do
      @movie = API.movie_by_id(238)
      visit movie_path(@movie)
      click_on "Create Event for #{@movie[:title]}"
      select "2021", from: "_day_1i"
      select "August", from: "_day_2i"
      select "30", from: "_day_3i"
      fill_in "start_time", with: "21:25"

      expect(Event.all.count).to eq(0)
      click_on "Create Party"

      expect(Event.all.count).to eq(1)
      expect(@user.events.last)
    end
  end
end
